version: "3.9"
services:
#  fav-food:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    ports:
#      - "8000:8000"
  db:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fav_food
      POSTGRES_USER: fav_food
      POSTGRES_PASSWORD: fav_food
    ports:
      - "5432:5432"
volumes:
  data: ~